/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bi.crypto.jshafs;

import org.junit.Test;
import static org.junit.Assert.*;

public class jshafsTest {
    @Test public void appHasAGreeting() {
        jshafs classUnderTest = new jshafs();

    }
}
